import type { AppointmentGroup } from "./types";

export const MOCK_GROUPS: AppointmentGroup[] = [
  {
    id: "grp-1",
    appointmentAt: new Date().toISOString().slice(0, 10) + "T09:00:00",
    performerId: "emp-1",
    performerName: "Иванов Алексей",
    sellableItemId: "svc-1",
    sellableItemName: "Групповое занятие (Йога)",
    price: 500,
    participants: [
      {
        id: "appt-1",
        patientId: "pat-1",
        patientName: "Смирнова Анна",
        status: "scheduled",
        total: 500,
        paidCash: 0,
        paidCard: 0,
        paidBalance: 0,
        paidBonuses: 0,
        debt: 500,
      },
      {
        id: "appt-2",
        patientId: "pat-2",
        patientName: "Козлов Дмитрий",
        status: "arrived",
        total: 500,
        paidCash: 500,
        paidCard: 0,
        paidBalance: 0,
        paidBonuses: 0,
        debt: 0,
      },
      {
        id: "appt-3",
        patientId: "pat-3",
        patientName: "Лебедева Мария",
        status: "paid",
        total: 500,
        paidCash: 0,
        paidCard: 500,
        paidBalance: 0,
        paidBonuses: 0,
        debt: 0,
      },
    ],
  },
  {
    id: "grp-2",
    appointmentAt: new Date().toISOString().slice(0, 10) + "T11:00:00",
    performerId: "emp-2",
    performerName: "Петрова Светлана",
    sellableItemId: "svc-2",
    sellableItemName: "Групповое занятие (Пилатес)",
    price: 700,
    participants: [
      {
        id: "appt-4",
        patientId: "pat-4",
        patientName: "Новиков Сергей",
        status: "scheduled",
        total: 700,
        paidCash: 0,
        paidCard: 0,
        paidBalance: 0,
        paidBonuses: 0,
        debt: 700,
      },
      {
        id: "appt-5",
        patientId: "pat-5",
        patientName: "Федорова Ольга",
        status: "not_came",
        total: 700,
        paidCash: 0,
        paidCard: 0,
        paidBalance: 0,
        paidBonuses: 0,
        debt: 0,
      },
    ],
  },
];
