$fontsDir = "src/assets/fonts"
$outputFile = "src/utility/custom_vfs.ts"

$fonts = @(
    "Roboto-Regular.ttf",
    "Roboto-Bold.ttf",
    "Roboto-Italic.ttf",
    "Roboto-Medium.ttf"
)

$vfs = @{}

Write-Host "Starting VFS generation..."

foreach ($font in $fonts) {
    $path = Join-Path $fontsDir $font
    if (Test-Path $path) {
        Write-Host "Processing: $font"
        $bytes = [System.IO.File]::ReadAllBytes($path)
        $base64 = [System.Convert]::ToBase64String($bytes)
        $vfs[$font] = $base64
    }
    else {
        Write-Error "Font not found: $font"
    }
}

$json = $vfs | ConvertTo-Json -Compress
$content = "// Automatically generated by scripts/generate-vfs.ps1`nexport const customVfs: Record<string, string> = $json;"

Set-Content -Path $outputFile -Value $content -Encoding utf8

Write-Host "Success! VFS saved to: $outputFile"
